# Generated by Django 3.2 on 2022-06-29 01:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('siglas', models.CharField(max_length=20)),
                ('encargado', models.CharField(max_length=80)),
                ('puesto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('siglas', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id_ficha', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('num_documento', models.CharField(max_length=200)),
                ('fecha_documento', models.DateTimeField(default=datetime.datetime.now)),
                ('nombre_firma', models.CharField(max_length=350)),
                ('asunto', models.CharField(max_length=500)),
                ('instruccion', models.TextField(max_length=800)),
                ('resolucion', models.TextField(max_length=800)),
                ('fecha_recibido', models.DateTimeField(default=datetime.datetime.now)),
                ('area_turnada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.area', verbose_name='Area')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.dependencia', verbose_name='Dependencia')),
            ],
        ),
    ]
