# Generated by Django 3.2 on 2022-07-26 02:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='encargado',
            field=models.CharField(max_length=80, verbose_name='Encargado'),
        ),
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='area',
            name='puesto',
            field=models.CharField(max_length=100, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='area',
            name='siglas',
            field=models.CharField(max_length=20, verbose_name='Siglas'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='siglas',
            field=models.CharField(max_length=20, verbose_name='Siglas'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='area_turnada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.area', verbose_name='Area a la que se turna'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='asunto',
            field=models.CharField(max_length=500, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.dependencia', verbose_name='Dependencia Procedente'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='fecha_documento',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha del Documento'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='fecha_recibido',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha y firma de quien recibe'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='id_ficha',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='No. de Ficha'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='instruccion',
            field=models.TextField(max_length=800, verbose_name='Instrucción'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='nombre_firma',
            field=models.CharField(max_length=350, verbose_name='Nombre de quien firma'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='num_documento',
            field=models.CharField(max_length=200, verbose_name='Número del Documento'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='resolucion',
            field=models.TextField(max_length=800, verbose_name='Resolución'),
        ),
    ]
