# Generated by Django 3.2 on 2022-07-26 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_auto_20220726_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='fecha',
            field=models.TimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='fecha_documento',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Fecha del Documento'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='fecha_recibido',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Fecha y firma de quien recibe'),
        ),
    ]
