name: Deploy to GitHub Actions

on:
  push:
    branches:
      - "develop"
  pull_request:
      branches: "develop"

permissions:
  contents: read

jobs:

  deploy:

    name: Deployment
    runs-on: ubuntu-latest
    environment: dev


    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v1

      - name: Verify MariaDB connection
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done  

      - name: Build the images and start the containers
        run: |
          ls -la
          docker ps -a
          echo "-------------------------------------"

          docker images -a
          echo "-------------------------------------"
          docker-compose down
          docker system prune --force --volumes
          docker-compose up -d
          docker-compose ps
          echo "-------------------------------------"
          sleep 5
          docker-compose ps

      - name: Stop containers
        if: always()
        run: docker-compose down